site_name: CIDA Research Tools Knowledge Base
nav:
 - Home: index.md
 - Contributing: contributing/CONTRIBUTING.md
 - CIDA Coding Guidelines:
   - coding_guidelines.md
   - data_storage.md
 - Programming Tutorials:
   - sas-macros.md
   - tabling_packages.md
 - Unix / Command Line Tutorials:
   - cron-jobs.md
 - Git and GitHub:
   - git/github_setup_01.md
   - git/github_basics_02.md
   - git/github_troubleshooting_03.md
   - git/git.md
 - Computing Resources:
   - compuitng/CIDA_computing_resources.md
   - computing/alpine.md
   - CSPH Biostats Cluster:
     - computing/CIDA_BIOS_Cluster.md
     - computing/CIDA_BIOS_Cluster_Interactive_IDEs.md
repo_url: https://github.com/CIDA-CSPH/CIDAtools
repo_name: CIDA-CSPH/CIDAtools
plugins:
 - search
theme:
 variant: classic
 palette:
  primary: indigo
  
